name: Log Commit Information

on:
  push:
    branches:
      - main
      - development

jobs:
  log_commit_info:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up PostgreSQL client
      run: sudo apt-get install -y postgresql-client

    - name: Log commit information to PostgreSQL
      env:
        PGHOST: ${{ secrets.CBS_HOST }}
        PGPORT: ${{ secrets.CBS_PORT }}
        PGUSER: ${{ secrets.CBS_USERNAME }}
        PGPASSWORD: ${{ secrets.CBS_WW }}
        PGDATABASE: ${{ secrets.CBS_DBNAME }}
        COMMIT_ID: ${{ github.sha }}
        AUTHOR_NAME: ${{ github.actor }}
        AUTHOR_EMAIL: ${{ github.event.head_commit.author.email }}
        BRANCH_NAME: ${{ github.ref_name }}
        COMMIT_MESSAGE: ${{ github.event.head_commit.message }}
        COMMITTED_AT: ${{ github.event.head_commit.timestamp }}
      run: |
        psql "host=$PGHOST port=$PGPORT dbname=$PGDATABASE user=$PGUSER password=$PGPASSWORD sslmode=require" \
        -c "INSERT INTO raw.commit_logs (commit_id, author_name, author_email, branch_name, commit_message, committed_at) \
            VALUES ('$COMMIT_ID', '$AUTHOR_NAME', '$AUTHOR_EMAIL', '$BRANCH_NAME', '$COMMIT_MESSAGE', '$COMMITTED_AT');"
