name: Running scripts on postgre

run-name: ${{ github.actor}} script is deploying to server

on:
    push:
        branches:
            - main

    workflow_dispatch:
            # hello
jobs:
    run-sql:
        runs-on: windows-latest

        steps:
            - name: checkout/copy code
              uses: actions/checkout@v2


            - name: Install postgres client
              run:  
                choco install postgresql
    

            - name: Set the path for postgre
              shell: powershell
              run: |
                $pathToAdd = "C:\Program Files\PostgreSQL\16\bin"
                $currentPath = [Environment]::GetEnvironmentVariable("PATH", "Machine")
                [Environment]::SetEnvironmentVariable("PATH", "$currentPath;$pathToAdd", "Machine")

            - name: Run the DDL scripts
              shell: powershell
              env:
                PGHOST: ${{ secrets.CBS_HOST }}
                PGPORT: ${{ secrets.CBS_PORT }}
                PGUSER: ${{ secrets.CBS_USERNAME }}
                PGPASSWORD: ${{ secrets.CBS_WW }}
                PGDATABASE: ${{ secrets.CBS_DBNAME }}

              run: |
                $env:PATH
                
                & "C:\Program Files\PostgreSQL\16\bin\psql" -f DDL/*.sql