name: Deploy to postgreServer

on:
    push:
        branches:
            - main
    workflow_dispatch:

jobs:
    Deploy_to_postgre:
        runs-on: windows-latest
        steps:
            - uses: actions/checkout@v2

            - name: install postgre sql client on runner
              run: choco install postgresql --yes

            - name: add postgre to path
              shell: cmd
              run: |
               setx path "%path%;C:\Program Files\PostgreSQL\13\bin"
               refreshenv

            - name: Run SQL scripts
              env: 
                PGHOST: ${{ secrets.CBS_HOSTN }}
                PGPORT: ${{ secrets.CBS_PORT }}
                PGUSER: ${{ secrets.CBS_USERNAME }}
                PGPASSWORD: ${{ secrets.CBS_WW }}
                PGDATABASE: ${{ secrets.CBS_DBNAME }}
              run: |
                $env:PGPASSWORD = "${{ secrets.CBS_WW }}"
                Get-ChildItem -Path DDL\*.sql | ForEach-Object {Write-Output "Running $($_.Fullname)..."
                  psql -h $env:PGHOST -p $env:PGPORT -d $env:PGDATABASE -f &_.Fullname}
