name: Sync DDl scripts

run-name: Syncing DDL scripts with main

on: 
    push:
         branches:
             - main
         paths:
             - DDL/**
    workflow_dispatch:

    
jobs:
    syncing-ddl:
        runs-on: ubuntu-latest

        steps:
            - name: Check the code
              uses: actions/checkout@v2


            - name: Install postgre client
              run: sudo apt-get update && sudo apt-get install -y postgresql-client

            - name: List contents of DDL
              run: ls -la $GITHUB_WORKSPACE/DDL

            - name: Sync with Database
              env:
                PGHOST: ${{ secrets.CBS_HOST }}
                PGPORT: ${{ secrets.CBS_PORT }}
                PGUSER: ${{ secrets.CBS_USERNAME }}
                PGPASSWORD: ${{ secrets.CBS_WW }}
                PGDATABASE: ${{ secrets.CBS_DBNAME }}
              run: |
                cd $GITHUB_WORKSPACE/DDL


                ddl_tables=$(for file in *.sql; do basename "$file" .sql; done)
                echo "DDL Tables: $ddl_tables"
                
                db_tables=$(psql -t -c "
                  SELECT tablename
                  FROM pg_tables
                  WHERE schemaname = 'public';")
                echo "Database Tables: $db_tables"

                for file in *.sql; do
                  table=$(basename "$file" .sql)
                  echo "Processing $table"

                  echo "Dropping table $table if it exists"
                  psql -c "DROP TABLE IF EXISTS \"$table\" CASCADE;"

                  echo "Running script $file"
                  psql -f "$file"
                done

                for table in $db_tables; do
                  if [[ ! " $ddl_tables " =~ " $table " ]]; then
                    echo "Dropping table $table as it is not in the DDL folder"
                    psql -c "DROP TABLE IF EXISTS \"$table\" CASCADE;"
                  fi
                done
                