# Deze workflow checks de git repo
# kijkt als die overeenkomt wat er in de slq server is
# als de slq server niet hetzelfde is gaat het  de tables die overeen komen verwijderen en dan opnieuw 
# crieren in de server met de ddl script


name: Sync DDl scripts

run-name: Syncing DDL scripts with main

on: 
    push:
         branches:
             - main
         paths:
             - DDL/**
    workflow_dispatch:

    
jobs:
    syncing-ddl:
        runs-on: ubuntu-latest

        steps:
            - name: Check the code
              uses: actions/checkout@v2


            - name: Install postgre client
              run: sudo apt-get update && sudo apt-get install -y postgresql-client

            - name: List contents of DDL
              run: ls -la $GITHUB_WORKSPACE/DDL

            - name: Sync with Database
              env:
                PGHOST: ${{ secrets.CBS_HOST }}
                PGPORT: ${{ secrets.CBS_PORT }}
                PGUSER: ${{ secrets.CBS_USERNAME }}
                PGPASSWORD: ${{ secrets.CBS_WW }}
                PGDATABASE: ${{ secrets.CBS_DBNAME }}
              run: |
                set -e  # Exit on error

                cd $GITHUB_WORKSPACE/DDL

                ddl_tables=$(for file in *.sql; do basename "$file" .sql; done)
                echo "DDL Tables: $ddl_tables"

                db_tables=$(psql -t -c "SELECT tablename FROM pg_tables WHERE schemaname = 'public';")
                echo "Database Tables: $db_tables"

                for file in *.sql; do
                  table=$(basename "$file" .sql)
                  echo "Processing $table"

                  if psql -t -c "SELECT EXISTS (SELECT 1 FROM information_schema.tables WHERE table_name = '$table');" | grep -q 't'; then
                    echo "Table $table exists, checking columns"

                    existing_columns=$(psql -t -c "SELECT column_name FROM information_schema.columns WHERE table_name = '$table';" | tr -d ' ' | tr '\n' ' ')
                    echo "Existing Columns: $existing_columns"

                    script_columns=$(grep -oP '^\s*\w+\s+\w+' "$file" | awk '{print $1}' | tr -d ' ' | tr '\n' ' ')
                    echo "Script Columns: $script_columns"

                    if [ "$existing_columns" != "$script_columns" ]; then
                      echo "Dropping table $table due to column mismatch"
                      psql -c "DROP TABLE IF EXISTS \"$table\" CASCADE;"
                    fi
                  fi

                  echo "Running script $file"
                  psql -f "$file"
                done

                for table in $db_tables; do
                  if [[ ! " $ddl_tables " =~ " $table " ]]; then
                    echo "Dropping table $table as it is not in the DDL folder"
                    psql -c "DROP TABLE IF EXISTS \"$table\" CASCADE;"
                  fi
                done
                