name: Sync DDl scripts

run-name: Syncing DDL scripts with main

on: 
    # push:
    #     branches:
    #         - main
    #     paths:
    #         - DDL/**
    workflow_dispatch:

    
jobs:
    syncing-ddl:
        runs-on: ubuntu-latest

        steps:
            - name: Check the code
              uses: actions/checkout@v2


            - name: Install postgre client
              run: sudo apt-get update && sudo apt-get install -y postgresql-client

            - name: List contents of DDL
              run: ls -la $GITHUB_WORKSPACE/DDL

            - name: Sync with Database
              env:
                PGHOST: ${{ secrets.CBS_HOST }}
                PGPORT: ${{ secrets.CBS_PORT }}
                PGUSER: ${{ secrets.CBS_USERNAME }}
                PGPASSWORD: ${{ secrets.CBS_WW }}
                PGDATABASE: ${{ secrets.CBS_DBNAME }}
              run: |
                cd $GITHUB_WORKSPACE/DDL

                for file in *.sql; do
                  tablename=$(basename "$file" .sql)
                  echo "Processing $tablename"

                  existing_columns=$(psql -t -c "
                    SELECT column_name || ' ' || data_type 
                    FROM information_schema.columns 
                    WHERE table_name = '$tablename' 
                    ORDER BY ordinal_position;")

                  ddl_columns=$(grep -oP '(\w+ \w+)(?=,|$)' "$file" | tr '\n' ',' | sed 's/,$//')

                  if [[ "$existing_columns" != "$ddl_columns" ]]; then
                    echo "Table $tablename structure mismatch. Dropping and recreating..."
                    psql -c "DROP TABLE IF EXISTS $tablename CASCADE;"
                    psql -f "$file"
                  else
                    echo "Table $tablename structure matches. No action needed."
                  fi
                 done