name: Test_postgrecode_and_fix


run-name: pushed script from ${{ github.actor}} is being tested and errors fixed(if applicable)

on: 
    push:
      branches:
        - Development
        
 
            

    workflow_dispatch:
    # Deze workflow is reusable in de toekomst
    workflow_call:
jobs:
    Test_Code:
        runs-on: windows-latest
        
        steps:
            - uses: actions/checkout@v2

            - name: set up pythion in vm
              uses: actions/setup-python@v2
              with:
                 python-version: '3.9'
            
            - name: Install sqlFluff 
              run: pip install sqlfluff

            - name: run sql fluff
              run: sqlfluff lint DDL/* --dialect postgres


    Try_to_fix_issues:
      runs-on: windows-latest
      needs: Test_Code
      if: ${{ failure() }}       
      steps:
      - name: donwload to vm
        uses: actions/checkout@v2
    
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'
      
      - name: Install sqlfluff
        run: pip install sqlfluff
    
      - name: Run sqlfluff fix command
        run: sqlfluff fix DDL/* --dialect postgres
        continue-on-error: true
      - name: Set enviroment actior based on actor
        id: set-env
        run: |
            If [ "${{ github.actor }}" == "KevkevCon" ]; then
                echo "::set-env name=GITEMAIL::${{ secrets.GITEMAIL_KEV }}"
                echo "::set-env name=GITUSER::${{ secrets.GIT_USER_KEV }}"
                echo "::set-env name=GH_TOKEN::${{ secrets.GH_TOKEN }}"
            elif [ "${{ github.actor }}" == "trisshh" ]; then
                echo "::set-env name=GITEMAIL::${{ secrets.GITEMAIL_TRISH }}"
                echo "::set-env name=GITUSER::${{ secrets.GIT_USER_TRISH }}"
                echo "::set-env name=GH_TOKEN::${{ secrets.GH_TOKEN_TRISH }}"
            else 
              echo "User not recongnized"
              exit 1 
            fi  

        
      - name: Commit changes
        run: |
         git config --global user.email "${{ env.GITEMAIL }}"
         git config --global user.name "${{ env.GITUSER }}"
         git add DDL/*
         git commit -m "Added automacit fix from ${{ github.actor }}"
         git push https://x-access-token:${{ env.GH_TOKEN }}@github.com/${{ github.repository }}.git HEAD:Development




